name = "telegram-wechat-bot"
main = "src/index-image.js"
compatibility_date = "2024-01-01"

# Development environment
[env.development]
name = "telegram-wechat-bot-dev"

# Production environment
[env.production.vars]
ENVIRONMENT = "production"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "wechat-bot-db"
database_id = "5c10a2c2-73ac-45db-a6d9-e170cc6e7331"

# Production environment
[env.production]
name = "telegram-wechat-bot-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "wechat-bot-db"
database_id = "5c10a2c2-73ac-45db-a6d9-e170cc6e7331"

# Environment variables
# Required secrets (set using: wrangler secret put <VARIABLE_NAME>):
# - TELEGRAM_BOT_TOKEN: Your Telegram Bot Token
# - SUPER_ADMIN_ID: Default super admin Telegram user ID
# Optional secrets:
# - ADMIN_API_KEY: Admin API key for management endpoints
# - TELEGRAPH_ACCESS_TOKEN: Telegraph account access token (will auto-create if not provided)

# Secrets setup commands:
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put SUPER_ADMIN_ID
# wrangler secret put ADMIN_API_KEY
# wrangler secret put TELEGRAPH_ACCESS_TOKEN

# Public environment variables
[vars]
# Bot configuration
BOT_NAME = "wechat2telegraphbot"
BOT_AUTHOR = "@wechat2telegraphbot"
BOT_DESCRIPTION = "Convert WeChat articles to Telegraph pages"

# Service endpoints
TELEGRAPH_API_URL = "https://api.telegra.ph"
JINA_AI_API_URL = "https://r.jina.ai"

# Default configuration
DEFAULT_LANGUAGE = "zh-CN"
MAX_IMAGE_SIZE = 10485760
REQUEST_TIMEOUT = 30000

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true